---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
    name: registry
    labels:
      app: registry
spec:
  hostNetwork: true
  containers:
  - name: registry
    image: registry:latest
    ports:
      - containerPort: 5000
    livenessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 3
      periodSeconds: 3
