apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: default
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  volumeName: example-pv
